### PR TITLE
add drop shadow to hudView

### PR DESCRIPTION
**Pull request by sammy-SC**

### CODE REVIEW

**Comment by famanson** [comment]
@sammy-SC is this the only change we made to the progress spinner?

**Comment by sammy-SC** [comment]
i think so.

**Comment by famanson** [comment]
@sammy-SC any chance you could do a diff of this one versus the one we have inside our code and spot any further differences?

**Comment by sammy-SC** [comment]
@famanson here it is.

```
902,905c902
<         _hudView.layer.masksToBounds = NO;
<         _hudView.layer.shadowColor = [UIColor blackColor].CGColor;
<         _hudView.layer.shadowOpacity = 0.4;
<         _hudView.layer.shadowOffset = CGSizeZero;
---
>         _hudView.layer.masksToBounds = YES;
```

**Comment by famanson** [comment]
@sammy-SC pls submit a separate PR to make the main iOS code use this as well

**Pull request merged**
